name: 'dbt_analytics_engine'
version: '1.0.0'

profile: 'dbt_analytics_engine'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["models"]
macro-paths: ["macros"]
docs-paths: ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_analytics_engine:
    +persist_docs:
      relation: true
      columns: true
    +meta:
      analytics_engineer: 'Moe Abbas'
    staging:
      +hours_to_expiration: "{{ 72 if target.name != 'prod' else none }}"
      +materialized: view
      +schema: 'staging'
    intermediate:
      +hours_to_expiration: "{{ 72 if target.name != 'prod' else none }}"
      +materialized: view
      +schema: 'staging'
      +docs:
        node_color: '#DEB41F'
    marts:
      +hours_to_expiration: "{{ 72 if target.name != 'prod' else none }}"
      +required_tests: {"unique.*|not_null": 2}
      +required_docs: true
      +materialized: table
      +docs:
        node_color: '#000000'
      cohorts:
        +schema: 'cohorts'
      customers:
        +schema: 'customers'
      finance:
        +schema: 'finance'
      product:
        +schema: 'product'
      sales:
        +schema: 'sales'


seeds:
  dbt_analytics_engine:
    +persist_docs:
      relation: true
      columns: true
    +schema: 'seeds'
    +docs:
      node_color: '#60BC24'

data_tests:
  dbt_analytics_engine:
    +severity: error
    +error_if: ">20"
    +warn_if: ">1"
    +limit: 1000
    +store_failures: "{{ true if target.name in ['prod', 'ci'] else false }}"
    +schema: 'zzz_failures'

flags:
  printer_width: 95
  send_anonymous_usage_stats: false
  indirect_selection: cautious